### DPVO BLT Config File ###

BUFFER_SIZE: 8192

PATCHES_PER_FRAME: 96
REMOVAL_WINDOW: 22
OPTIMIZATION_WINDOW: 10
PATCH_LIFETIME: 13

KEYFRAME_THRESH: 15.0

MOTION_MODEL: 'DAMPED_LINEAR'
MOTION_DAMPING: 0.5

MIXED_PRECISION: True

LOOP_CLOSURE: False

CENTROID_SEL_STRAT: 'RANDOM'

CAM_MONO: 'rgb_0'
