exp_bacchus_360_dpvo_no_loop:
  Config: config_bacchus.yaml
  NumRuns: 1
  Parameters: {mode: mono, verbose: 0, settings_yaml: configs/baselines/dpvo_bacchus_no_loop.yaml}
  Module: dpvo

exp_bacchus_360_dpvo_loop:
  Config: config_bacchus.yaml
  NumRuns: 1
  Parameters: {mode: mono, verbose: 0, settings_yaml: configs/baselines/dpvo_bacchus_loop.yaml}
  Module: dpvo
